### ISSUE TITLE
Faixa etária sendo mostrada ERRADA

### ISSUE THREAD

**Issue by marcos-mendez** [popsolutions/bailaki-app#17]
Quando alterei a faixa etaria de 25 ate 45 anos ele alterou no backend, porém no fronte-end continua mostrando errado 18 ate 99 
![Screenshot from 2021-05-19 22-50-15](https://user-images.githubusercontent.com/38361760/118906711-ac77de80-b8f4-11eb-9bff-957e2ced39e4.png)

**Comment by rullyalves** [comment]
resolvido no PR aberto.
